### ISSUE TITLE
The test for area of a circle is broken

### ISSUE THREAD

**Issue by szrharrison** [learn-co-curriculum/javascript-inheritance-patterns-lab#5]
uses `Math.PI * c.radius^2` instead of `Math.PI *c.radius ** 2` to calculate the area of a circle. This causes it to expect the area to be 4 instead of 12.56637...

**Comment by kjleitz** [comment]
+1

`^` is bitwise XOR, not an exponent operator. The test thinks a circle with a radius of 2 should have an area of 4.

**Comment by samnags** [comment]
@aturkewi Theses issues are accurate.
